#!/bin/sh
# Writes the Homebrew formula (CLI) and cask (desktop app) for a published release into a
# checkout of the tap repository aleslanik2/homebrew-nepomuk.
#
#   scripts/update-homebrew.sh v0.4.4 ../homebrew-nepomuk
#
# The hashes come only from a SHA256SUMS whose release signature verifies against the key in
# install.sh: Homebrew checks downloads against the formula, so the formula is the trust anchor
# for brew users. Review the diff in the tap, then commit and push it.

set -eu

tag="${1:?usage: update-homebrew.sh <tag> <tap checkout>}"
tap="${2:?usage: update-homebrew.sh <tag> <tap checkout>}"
repo="aleslanik2/nepomuk"
root=$(cd "$(dirname "$0")/.." && pwd)
version="${tag#v}"

case "$tag" in
    v[0-9]*.[0-9]*.[0-9]*) ;;
    *) echo "not a release tag: $tag" >&2; exit 1 ;;
esac
[ -d "$tap" ] || { echo "no tap checkout at $tap" >&2; exit 1; }

work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

gh release download "$tag" -R "$repo" -D "$work" -p SHA256SUMS -p SHA256SUMS.sig
"$root/scripts/release-signers.sh" verify "$work/SHA256SUMS" "$work/SHA256SUMS.sig"

sha() { # asset
    h=$(awk -v f="$1" '$2 == f || $2 == "*" f { print $1 }' "$work/SHA256SUMS")
    case "$h" in
        [0-9a-f]*) [ ${#h} -eq 64 ] && { printf '%s' "$h"; return; } ;;
    esac
    echo "SHA256SUMS of $tag does not list $1" >&2
    exit 1
}

cli_mac_arm=$(sha "nepomuk-$tag-aarch64-apple-darwin.tar.gz")
cli_mac_intel=$(sha "nepomuk-$tag-x86_64-apple-darwin.tar.gz")
cli_linux_arm=$(sha "nepomuk-$tag-aarch64-unknown-linux-musl.tar.gz")
cli_linux_intel=$(sha "nepomuk-$tag-x86_64-unknown-linux-musl.tar.gz")
gui_arm=$(sha "nepomuk-gui-$tag-aarch64-apple-darwin.dmg")
gui_intel=$(sha "nepomuk-gui-$tag-x86_64-apple-darwin.dmg")

base="https://github.com/$repo/releases/download/$tag"
mkdir -p "$tap/Formula" "$tap/Casks"

cat >"$tap/Formula/nepomuk.rb" <<EOF
# Generated by scripts/update-homebrew.sh in $repo from the signed SHA256SUMS of $tag.
class Nepomuk < Formula
  desc "Post-quantum secrets vault in a single file in git"
  homepage "https://github.com/$repo"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "$base/nepomuk-$tag-aarch64-apple-darwin.tar.gz"
      sha256 "$cli_mac_arm"
    end
    on_intel do
      url "$base/nepomuk-$tag-x86_64-apple-darwin.tar.gz"
      sha256 "$cli_mac_intel"
    end
  end

  on_linux do
    on_arm do
      url "$base/nepomuk-$tag-aarch64-unknown-linux-musl.tar.gz"
      sha256 "$cli_linux_arm"
    end
    on_intel do
      url "$base/nepomuk-$tag-x86_64-unknown-linux-musl.tar.gz"
      sha256 "$cli_linux_intel"
    end
  end

  def install
    bin.install "nepomuk"
    # The CLI runs the Touch ID helper only from its own folder.
    bin.install "nepomuk-touchid" if OS.mac?
  end

  def caveats
    <<~TEXT
      Update with \`brew upgrade nepomuk\`, not \`nepomuk upgrade\`.
    TEXT
  end

  test do
    assert_match "nepomuk #{version}", shell_output("#{bin}/nepomuk version")
  end
end
EOF

cat >"$tap/Casks/nepomuk-gui.rb" <<EOF
# Generated by scripts/update-homebrew.sh in $repo from the signed SHA256SUMS of $tag.
cask "nepomuk-gui" do
  arch arm: "aarch64", intel: "x86_64"

  version "$version"
  sha256 arm:   "$gui_arm",
         intel: "$gui_intel"

  url "$base/nepomuk-gui-v#{version}-#{arch}-apple-darwin.dmg"
  name "nepomuk"
  desc "Desktop app for the nepomuk post-quantum secrets vault"
  homepage "https://github.com/$repo"

  depends_on :macos

  app "nepomuk.app"

  # The app is not notarized yet, so Gatekeeper would refuse to open it. Homebrew has checked
  # the download against the hash from the signed SHA256SUMS; install.sh clears the flag the
  # same way after the same check.
  postflight_steps do
    run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{appdir}}/nepomuk.app"]
  end

  zap trash: [
    "~/Library/Application Support/com.github.aleslanik2.nepomuk",
    "~/Library/Caches/com.github.aleslanik2.nepomuk",
    "~/Library/WebKit/com.github.aleslanik2.nepomuk",
  ]
end
EOF

echo "Wrote $tap/Formula/nepomuk.rb and $tap/Casks/nepomuk-gui.rb for $tag"
